version: '3.7'

services:

    db:
        image: postgres:11
        environment:
        - PGDATA=/var/lib/postgresql/data/pgdata
        - POSTGRES_USER=mastermind
        - POSTGRES_DB=mastermind
        - POSTGRES_PASSWORD=mastermind
        ports:
        - "5432:5432"
        volumes:
        - db-data:/var/lib/postgresql/data/pgdata

volumes:
    db-data:

